version: '2'
services:
  mongo:
    image: mongo:3
    user: mongodb
  elasticsearch:
    image: elasticsearch:2
    command:
    - elasticsearch
    - -Des.cluster.name=graylog
  graylog:
    image: graylog2/server
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://externalIP/api
    ports:
    - 80:9000/tcp
    - 12201:12201/udp
    - 5044:5044/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: DATA=true
